### ISSUE TITLE
Issues in dissertations database paleoanthro

### ISSUE THREAD

**Issue by PresidentNick** [dennereed/paleoanthro#21]
All the pointers to files in the database have been added, here are remaining issues:

1. Alexander Mackay has two thesis volumes that need to be merged, they have been uploaded to box
2. Tracey Crummet is missing an abstract
3.  William Andrew Barr is missing an abstract
4.  Ian Jacob Wallace abstract and thesis files don't exist
5. Emanuelle Cancellieri thesis file doesn't exist
6. Virginia Hutton abstract and thesis files don't exist
7. Aurelien Mounier abstract and thesis files don't exist
8. Jeremy DeSilva thesis file doesn't exist
9. Christopher Gilbert abstract and thesis files don't exist
10. Rebecca Jabbour abstract and thesis files don't exist
11. Michael Masters abstract and thesis files don't exist
12. Utsav Schurmans abstract and thesis files don't exist
13. Matthew Skinner abstract and thesis files don't exist
14. Robert Stallman abstract file doesn't exist
15. Emmanuel Cleuvenot abstract and thesis files don't exist
16. Abdeljalil Bouzouggar abstract and thesis files don't exist

**Comment by PresidentNick** [comment]
Tracey Crummet doesn't have an abstract in the dissertations zip

**Comment by dennereed** [comment]
Yep, never have had that one.

On February 23, 2015 at 10:32:38 AM, Nick (notifications@github.com) wrote:

Tracey Crummet doesn't have an abstract in the dissertations zip

**Comment by PresidentNick** [comment]
William Andrew Barr also doesn't have one in the folder

**Comment by PresidentNick** [comment]
Got your email, uploaded it

**Comment by PresidentNick** [comment]
All uploaded except the missing Tracey Crummet
